### ISSUE TITLE
failed for intron_group

### ISSUE THREAD

**Issue by dipingxian431** [songlab-cal/scquint#8]
Thank you for the tools.

When I run `adata = group_introns(adata, by="three_prime")`. there is an error report. Can you help me to solve it?

```
>>> adata = add_gene_annotation(adata, "/data/Mingchao/Reference/GRCh38_GTF_GENCODE/gencode.v44.basic.annotation.gtf")
Filtering to introns associated to 1 and only 1 gene.
/home/mingchao/miniconda3/envs/scQuint/lib/python3.12/site-packages/scquint/data.py:129: ImplicitModificationWarning: Trying to modify attribute `.var` of view, initializing view as actual.
  adata.var["gene_id"] = adata.var.gene_id_list
>>> adata = group_introns(adata, by="three_prime")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mingchao/miniconda3/envs/scQuint/lib/python3.12/site-packages/scquint/data.py", line 141, in group_introns
    adata.var["intron_group"] = adata.var.apply(
    ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/mingchao/miniconda3/envs/scQuint/lib/python3.12/site-packages/pandas/core/frame.py", line 4301, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/mingchao/miniconda3/envs/scQuint/lib/python3.12/site-packages/pandas/core/frame.py", line 4459, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column intron_group
```

Thank you so much.

**Comment by apdavid** [comment]
I also encountered a similar error

When I run `adata = group_introns(adata, by = "three_prime")` I am using a `smartseq2` dataset

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/sp/572lqj8j0jq1wf3m2ljnzrl00000gq/T/ipykernel_36928/1241212862.py in ?()
      2     dir_path = os.path.join(path, directory, "output", "SJ", "raw")
      3     print("Path to SJ output: ", str(dir_path))
      4     adata = load_adata_from_starsolo(dir_path, var_filename ="genes.tsv")
      5     adata = add_gene_annotation(adata, "gencode.vM31.primary_assembly.annotation.gtf.gz")
----> 6     adata = group_introns(adata, by="three_prime")
      7     output_file = os.path.join(output_dir, f"{directory}_adata_spl.h5ad")
      8     print("Output File:", str(output_file))
      9     adata.write_h5ad(output_file)

~/scquint_sgn_alt_splicing/.venv/lib/python3.10/site-packages/scquint/data.py in ?(adata, by, filter_unique_gene_per_group)
    139 def group_introns(adata, by="three_prime", filter_unique_gene_per_group=True):
    140     if by == "three_prime":
--> 141         adata.var["intron_group"] = adata.var.apply(
    142             lambda intron: intron.chromosome
    143             + "_"
    144             + (str(intron.end) if intron.strand == "+" else str(intron.start))

~/scquint_sgn_alt_splicing/.venv/lib/python3.10/site-packages/pandas/core/frame.py in ?(self, key, value)
   4297             self._setitem_frame(key, value)
   4298         elif isinstance(key, (Series, np.ndarray, list, Index)):
   4299             self._setitem_array(key, value)
   4300         elif isinstance(value, DataFrame):
-> 4301             self._set_item_frame_value(key, value)
   4302         elif (
   4303             is_list_like(value)
   4304             and not self.columns.is_unique

~/scquint_sgn_alt_splicing/.venv/lib/python3.10/site-packages/pandas/core/frame.py in ?(self, key, value)
   4455 
   4456             return self.isetitem(locs, value)
   4457 
   4458         if len(value.columns) > 1:
-> 4459             raise ValueError(
   4460                 "Cannot set a DataFrame with multiple columns to the single "
   4461                 f"column {key}"
   4462             )

ValueError: Cannot set a DataFrame with multiple columns to the single column intron_group
```
